// The following spaghetti code was generated by ChatGPT

function setup() {
    createCanvas(400, 400);
    background(255);
}

function draw() {
    if (mouseIsPressed) {
        let r = random(255);
        let g = random(255);
        let b = random(255);
        strokeWeight(random(10));
        stroke(r, g, b);
        let size = random(50);
        let offsetX = random(20);
        let offsetY = random(20);
        let mode = int(random(3));

        if (mode == 0) {
            ellipse(mouseX + offsetX, mouseY + offsetY, size, size);
        } else if (mode == 1) {
            rect(mouseX + offsetX, mouseY + offsetY, size, size);
        } else {
            line(mouseX, mouseY, mouseX + offsetX, mouseY + offsetY);
        }
    }

    if (keyIsPressed) {
        if (key == 'c') {
            background(255);
        } else if (key == 'r') {
            let numRectangles = random(10) + 5;
            for (let i = 0; i < numRectangles; i++) {
                let x = random(width);
                let y = random(height);
                let w = random(100);
                let h = random(100);
                let red = random(255);
                let green = random(255);
                let blue = random(255);
                fill(red, green, blue);
                rect(x, y, w, h);
            }
        }
    }
}
  